[package]
name = "web-gcd-calculator"
version = "0.1.0"
authors = ["Srjkaa <srjkaa@yandex.by>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
